import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Nav";
import { Web3ReactProviderWrapper } from "./providers/Web3Provider";
import ThreeCanvas from "@/components/ThreeCanvas";
import BuySection from "@/components/BuySection";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="antialiased relative min-h-screen bg-dark-light text-gray-900 p-6"
    >
      <Web3ReactProviderWrapper>
        <body className={`${geistSans.variable} ${geistMono.variable} `}>
          <ThreeCanvas />

          <NavBar />
          <main className="relative  mx-auto z-1">
            <BuySection />

            {children}
          </main>
        </body>
      </Web3ReactProviderWrapper>
    </html>
  );
}
